# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('PK', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
